### PR TITLE
Seperate modules for functions.

### PR DESCRIPTION
**Pull request by roryyarr**
Creates separate modules for functions.

### CODE REVIEW

**Review by harleym — COMMENTED** [review]
LPPProblem does not live in presolve module.
Use the lp_llama_ipm.ipynb NOT the older prototype
lp_llama_ipm.ipynb is designed to be command line after running nb_to_jl.py
main.jl is not required
Use the new version of read_mps_from string

**Comment by roryyarr** [comment]
Added changes.

**Review by harleym — COMMENTED** [review]
Remove the LPProblem from read_mps.jl
Export goes straight after the module declaration

**Comment by roryyarr** [comment]
Add unit testing for read_mps.

**Review by harleym — COMMENTED** [review]
using SparseArrays should be in lp_problem.jl
using .lpProblem: LPProblem - just using .lpProblem <- bring in all export

**Comment by roryyarr** [comment]
Added SparseArrays and Random and other changes.

**Review by harleym — APPROVED** [review]

**Pull request merged**
